### ISSUE TITLE
安全漏洞提醒

### ISSUE THREAD

**Issue by code6er** [roachsinai/dotfiles#1]
漏洞类型：邮箱 SMTP 信息泄露

漏洞等级：高

漏洞地址：https://github.com/roachsinai/dotfiles/blob/6736592a4e7d196c1476830f757c588d9f45b319/dotfiles/Documents/scripts/check_notifications.py

漏洞危害：任何人可以通过 SMTP 账号密码收发邮件，进而通过邮箱重置其他平台密码

解决方案：重置 SMTP 密码并检查邮箱是否有敏感信息泄露（请勿只修改代码，历史版本库依旧可见）

本次扫描结果由 [ 码小六 ] https://github.com/4x99/code6 提供（欢迎 star）

**Comment by roachsinai** [comment]
感谢，已经删除曝光的授权码。

**Comment by roachsinai** [comment]
下面就记录一下同样的问题如何解决：

1. 在本地仓库修改对应的文件，之后提交之后通过rebase删除或者squash之前的commit
2. git push -f
3. 联系github团队删除github上对应的commit（也就是说只要push到github上的提交，github都会缓存）

如果涉及的文件多，或这commit多，就访问[从仓库中删除敏感数据 - GitHub 帮助](https://help.github.com/cn/github/authenticating-to-github/removing-sensitive-data-from-a-repository)。按照该网页中的内容操作。

该页面中有如何联系github团队人员删除commit的方法。

---

需要注意的是本地的reflog中还是会有之前的commit需要通过一下方式删除：

```
# https://stackoverflow.com/a/4528593/6074780
git reflog expire --expire-unreachable=now --all # 这个同样会删除掉stash，因为stash也是一个commit，需要注意
git gc --prune=now
```
